// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS1sTeXxSfJrdOxRdBS9pV7rh5WbaMacY',
    appId: '1:726462676449:web:a161854bf01f3960b526a0',
    messagingSenderId: '726462676449',
    projectId: 'sakhii-de23e',
    authDomain: 'sakhii-de23e.firebaseapp.com',
    storageBucket: 'sakhii-de23e.appspot.com',
    measurementId: 'G-MFT8F9RJB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBptNAkOKr2_n_RC90LnaqT1T-2qRmqqJI',
    appId: '1:726462676449:android:09ad9d3ca9b8972bb526a0',
    messagingSenderId: '726462676449',
    projectId: 'sakhii-de23e',
    storageBucket: 'sakhii-de23e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu_Rs-7-gWizseDSDtCgN4FoCZNtUV9UU',
    appId: '1:726462676449:ios:6c06a32d9c150a97b526a0',
    messagingSenderId: '726462676449',
    projectId: 'sakhii-de23e',
    storageBucket: 'sakhii-de23e.appspot.com',
    iosBundleId: 'in.abhi6722.sakhii',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu_Rs-7-gWizseDSDtCgN4FoCZNtUV9UU',
    appId: '1:726462676449:ios:a177f83eb16e9663b526a0',
    messagingSenderId: '726462676449',
    projectId: 'sakhii-de23e',
    storageBucket: 'sakhii-de23e.appspot.com',
    iosBundleId: 'in.abhi6722.sakhii.RunnerTests',
  );
}
